### ISSUE TITLE
When i compare with Empty version string Getting Error 

### ISSUE THREAD

**Issue by vinaykumarva** [hashicorp/go-version#132]
```go
v1, _ := version.NewVersion("")
	v2, _ := version.NewVersion("10.3")
	if v1.LessThan(v2) {
		fmt.Println("v1<v2")
	} else {
		fmt.Println("v2<v1")
	}
```

<nil>
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x4a3bd3]

goroutine 1 [running]:
github.com/hashicorp/go-version.(*Version).String(0x0)
        /go/pkg/mod/github.com/hashicorp/go-version@v1.6.0/version.go:369 +0x33
github.com/hashicorp/go-version.(*Version).Compare(0xc000080140, 0x0)
        /go/pkg/mod/github.com/hashicorp/go-version@v1.6.0/version.go:116 +0x39
github.com/hashicorp/go-version.(*Version).GreaterThan(...)
        /go/pkg/mod/github.com/hashicorp/go-version@v1.6.0/version.go:298
main.main()
        /workspaces/learning/rc/string.go:18 +0x95
exit status 2

**Comment by radeksimko** [comment]
This library is designed with the expectation that raw versions are validated well before the input is passed into the parser. Typically, application code is better positioned to do such validation.

e.g. if you have UI which expects version input from a user, it would do this via frontend (HTML or JavaScript), similarly, CLI would return a _user facing_ error with the appropriate Unix exit code. If the interface is HTTP API, then the whole request would get validated and appropriate HTTP error returned.

That's not to say the library _could not_ return error - just that we'd need a good reason to do so and with the above in mind I cannot think of one.
