### ISSUE TITLE
Errors with Debian versions

### ISSUE THREAD

**Issue by sevagh** [hashicorp/go-version#57]
Hello - I'm running into some trouble with Debian package versioning. The trailing `+deb8u92`-style patch notations aren't taken into account:

```go
package main

import (
	"fmt"

	"github.com/hashicorp/go-version"
)

func main() {
	v1, _ := version.NewVersion("1.5+deb8u9")
	v2, _ := version.NewVersion("1.5+deb8u7")

	fmt.Printf("%d\n", v1.Compare(v2))
	fmt.Printf("%+v\n", v1.Segments64())
}
```
Output:
```
0
[1 5 0]
```
Also, leading `1:` Epochs cause panics:
```go
package main

import (
	"fmt"

	"github.com/hashicorp/go-version"
)

func main() {
	v3, _ := version.NewVersion("1.3+deb8u7")
	v4, _ := version.NewVersion("2:1.3+deb8u7")

	fmt.Printf("%+v\n", v4.Segments64())
	fmt.Printf("%d\n", v3.Compare(v4))
}
```
Output:
```
shanssian:hashicorp-version-problem $ go run test.go
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x4af950]

goroutine 1 [running]:
github.com/hashicorp/go-version.(*Version).Segments64(...)
        /home/shanssian/go/src/github.com/hashicorp/go-version/version.go:344
main.main()
        /home/shanssian/scratch/hashicorp-version-problem/test.go:13 +0x90
exit status 2
```

**Comment by sevagh** [comment]
Didn't read closely enough that this is only for SemVer.
